### ISSUE TITLE
no luarocks in

### ISSUE THREAD

**Issue by Supernerd11** [DhavalKapil/luaver#14]
Whenever I start a new terminal session it writes 
`/usr/bin/which: no luarocks in (/home/jonathan/.luaver/lua/5.1.5/bin:/home/jonathan/.nvm/versions/node/v6.4.0/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/jonathan/.local/bin:/home/jonathan/bin)
` at the top. My guess is that it can't find luarocks in path.

**Comment by DhavalKapil** [comment]
Does this happen 'just' as you start a new terminal session? Could you show me the contents of your `~/.bashrc` or `~/.zshrc` file?

**Comment by Supernerd11** [comment]
I solved it by installing luarocks with my package manager too. It works now

**Comment by DhavalKapil** [comment]
Even if `luarocks` is not installed, this error should not come. Anyways, if you face the same error again, feel free to ping here.
