### ISSUE TITLE
Suggestion: dash compatibility

### ISSUE THREAD

**Issue by umireon** [DhavalKapil/luaver#24]
`dash` is the default implementation of `/bin/sh` in Debian and Ubuntu and is a POSIX-compliant shell.

Making luaver dash-compatible will elegantly solve every portability issue such as on zsh and on macOS.

I think this is easy for luaver because luaver does not heavily use bash-specific features.

**Comment by DhavalKapil** [comment]
I'll have to look into detail regarding this. Don't know much about `dash`.

**Comment by umireon** [comment]
Note that [nvm](https://github.com/creationix/nvm/blob/master/nvm.sh), the version manager for `nodejs` (server side javascript) is dash-compatible and thus works on sh, bash, ksh and, zsh.
IMO this approach is best to support multiple shell environments.

**Comment by DhavalKapil** [comment]
Looks good to me. Thanks, I'll definitely look into it by next week!

**Comment by umireon** [comment]
So I must add a mention to [shellcheck](https://www.shellcheck.net).
This is a reliable lint tool to check if the script is dash-compatible (or bash, zsh, or POSIX sh).
Bonus: there never be any escaping problem with shellcheck, since they can point out every problematic quoting.

**Comment by DhavalKapil** [comment]
I have enabled shellcheck test and edited the entire script accordingly. I'm planning to release a new version now. Let me know if you think anything else is required(especially focusing portability).

**Comment by umireon** [comment]
The list command will be broken if `ls` is aliased (#30), which is frequency true.

There still be problems such as bare `cat` and the dependency on the behavior which is not (probably) defined in POSIX (#29).
However, all of them except #30 is so minor that these should be disscussed after a new release.

**Comment by DhavalKapil** [comment]
I guess we are done with compatibility related changes right @umireon ?

**Comment by umireon** [comment]
Of course! 👍
