### ISSUE TITLE
Problems installing with zsh

### ISSUE THREAD

**Issue by hishamhm** [DhavalKapil/luaver#35]
Tried installing it with the `curl` line from README.md, and got this error:

```
==>  Detected SHELL_TYPE: zsh
set_up_path:7: = not found
```

After that, I'm in the `~/.luaver` directory, but typing the `luaver` command does nothing.

I launched `bash`, reran the `curl` installation line, and things worked as expected.

**Comment by DhavalKapil** [comment]
Hi, I guess you tried this with version 1.0.0 which was not compatible with `zsh`. The present `master` version should work fine. Try:

```sh
curl https://raw.githubusercontent.com/dhavalkapil/luaver/master/install.sh -o install.sh && . ./install.sh
```

**Comment by JaredSartin** [comment]
Can we get a release? Would love to update the homebrew!

**Comment by DhavalKapil** [comment]
I guess it has been a long time since a release was planned! I'll try to review all PRs and clean up content asap!

**Comment by JaredSartin** [comment]
Cheers - tagging #11 as this also is pertinent there too!

**Comment by JaredSartin** [comment]
@DhavalKapil Another ping... Version update with support here? You have built a great tool, I REALLY want to bring it into environments that have mixed ZSH/Bash use.

**Comment by DhavalKapil** [comment]
@JaredSartin thanks for pinging :smile: I've released 1.1.0. Feel free to update the homebrew!

**Comment by JaredSartin** [comment]
Cheers! Will do

**Comment by DhavalKapil** [comment]
Closing this now. Let me know if you still face this issue.
