### ISSUE TITLE
Feature request: cd back to original directory

### ISSUE THREAD

**Issue by hishamhm** [DhavalKapil/luaver#36]
It would be nicer if the `install.sh` script ran `cd` back to the original directory where I was originally, instead of leaving the shell at `~/.luaver`. Perhaps it could also print in the end something like 

```

Installation successful!
You can now run 'luaver' to see available commands.

```

**Comment by DhavalKapil** [comment]
The latest version of install script does show an installation successful message and `cd` back to the present directory. Can you try it once with the new script(in `master`) and if you face the same issue can you specify the steps that reproduced the error?

Thanks!

**Comment by DhavalKapil** [comment]
Closing this now. Let me know if you still face this issue.
