### ISSUE TITLE
can not compile on Macbook air

### ISSUE THREAD

**Issue by Yongke** [DhavalKapil/luaver#38]
uname of my macbook air is Darwin.
it should map to the platform macosx, but it's detected as linux.

**Comment by DhavalKapil** [comment]
Hi, can you give the output of this command on your system `uname -s` ?

Are you sure that you are using the latest code of luaver(in master branch)? How are you trying to install it?

**Comment by Yongke** [comment]
You are right. Just found that I'm using the older version.
```
curl https://raw.githubusercontent.com/dhavalkapil/luaver/v1.0.0/install.sh -o install.sh && . ./install.sh
```

The master is ok now.

**Comment by DhavalKapil** [comment]
Thanks :)
