### ISSUE TITLE
Named virtual environment

### ISSUE THREAD

**Issue by italomaia** [DhavalKapil/luaver#39]
It would be quite nice to be able to create named virtualenvironments with luaver, just like in python. Sometimes, one has multiple projects with multiple incompatible dependencies for the same lua version.

**Comment by DhavalKapil** [comment]
Can you be elaborate and see how it compares with #10.

**Comment by italomaia** [comment]
@DhavalKapil #10 is pretty much the same as #39 Thanks for pointing out.

**Comment by DhavalKapil** [comment]
Cool :smile:
